name: Deploy to AWS

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Debugging
        run: echo "${{ secrets.AWS_PRIVATE_KEYS }}"
        
      - name: Deploy to AWS
        run: |
          git clone --depth=1 --branch=main https://github.com/sunnykarthik507/django.git /tmp/deploy
          rsync -r --delete /tmp/deploy ubuntu@ec2-51-20-129-103.eu-north-1.compute.amazonaws.com:/var/www/html/

        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEYS }}